# Generated by Django 4.2.18 on 2025-02-25 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('matricula', models.AutoField(help_text='Informe a matrícula do Aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do Aluno', max_length=70)),
                ('data_inicial', models.DateField(default=django.utils.timezone.now, help_text='Informe a data inicial de matrícula do Aluno')),
                ('data_final', models.DateField(blank=True, help_text='Informe a data final de matrícula do Aluno', null=True)),
            ],
            options={
                'ordering': ['matricula'],
            },
        ),
    ]
