# Generated by Django 4.2.18 on 2025-02-14 23:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrutor', '0001_initial'),
        ('alunos', '0001_initial'),
        ('tipodeatividade', '0003_alter_tipodeatividade_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('numero', models.AutoField(help_text='Número da Turma', primary_key=True, serialize=False)),
                ('horarioAula', models.TimeField(help_text='Informe o horário da Aula')),
                ('duracaoAula', models.DurationField(help_text='Informe o horário da Aula')),
                ('dataInicial', models.DateField(default=datetime.datetime(2025, 2, 14, 23, 27, 15, 293464, tzinfo=datetime.timezone.utc), help_text='Informe a Data inicial')),
                ('dataFinal', models.DateField(default=datetime.datetime(2025, 2, 14, 23, 27, 15, 293464, tzinfo=datetime.timezone.utc), help_text='Informe a Data inicial')),
                ('codigoTipoAtividade', models.ForeignKey(blank=True, help_text='codigo do tipo de atividade da Turma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipodeatividade.tipodeatividade')),
                ('idInstrutor', models.ForeignKey(help_text='Identidade do Instrutor da Turma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instrutor.instrutor')),
                ('matriculaMonitor', models.ForeignKey(blank=True, help_text='Matrícula do Monitor da Turma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.alunos')),
            ],
        ),
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_matricula', models.DateField(default=django.utils.timezone.now, help_text='Data da matrícula do alino na turma')),
                ('data_fim_matricula', models.DateField(help_text='Data de fim de matrícula do aluno na turma', null=True)),
                ('matricula_aluno', models.ForeignKey(help_text='Matrícula do aluno da turma.', on_delete=django.db.models.deletion.CASCADE, to='alunos.alunos')),
                ('numero_turma', models.ForeignKey(help_text='Número da turma do aluno.', on_delete=django.db.models.deletion.CASCADE, to='turmas.turmas')),
            ],
        ),
    ]
