# Generated by Django 4.2.18 on 2025-02-15 00:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('turmas', '0004_alter_turmas_datafinal_alter_turmas_datainicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmas',
            name='dataInicial',
            field=models.DateField(default=datetime.datetime(2025, 2, 15, 0, 25, 19, 191059, tzinfo=datetime.timezone.utc), help_text='Informe a Data inicial'),
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ausencia', models.DateField(default=datetime.datetime(2025, 2, 15, 0, 25, 19, 192059, tzinfo=datetime.timezone.utc), help_text='Data da falta do aluno na turma')),
                ('matricula_aluno', models.ForeignKey(help_text='Matrícula do aluno da turma.', on_delete=django.db.models.deletion.CASCADE, to='alunos.alunos')),
                ('numero_turma', models.ForeignKey(help_text='Número da turma do aluno.', on_delete=django.db.models.deletion.CASCADE, to='turmas.turmas')),
            ],
        ),
    ]
